export const metadata = {
  title: 'Movies',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
